import '@/styles/globals.css';

import { Inter } from 'next/font/google';
import { headers } from 'next/headers';
import { Toaster } from '@/components/ui/sonner';

import { TRPCReactProvider } from '@/trpc/react';
import DesignerContextProvider from '@/components/context/designer-context';
import Provider from '@/components/context/client-provider';
import { getServerAuthSession } from '@/server/auth';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans'
});

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerAuthSession();

  return (
    <html lang='en'>
      <body className={`h-full font-sans ${inter.variable}`}>
        <TRPCReactProvider headers={headers()}>
          <Provider session={session}>{children}</Provider>
        </TRPCReactProvider>
        <Toaster richColors position='top-right' />
      </body>
    </html>
  );
}
