import '@/styles/globals.css';

import { Inter } from 'next/font/google';
import { headers } from 'next/headers';

import { TRPCReactProvider } from '@/trpc/react';
import DesignerContextProvider from '@/components/context/designer-context';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans'
});

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`font-sans ${inter.variable}`}>
        <DesignerContextProvider>
          <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
        </DesignerContextProvider>
      </body>
    </html>
  );
}
